#!/usr/bin/env bash
# List all running processes with detailed info and process hierarchy

echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT STARTED   TIME COMMAND"
ps -eo user,pid,pcpu,pmem,vsz,rss,tty,stat,stime,time,command --forest --no-headers
